# Generated by Django 6.0.6 on 2026-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_branch_address_ar_branch_address_en_branch_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='google_map',
        ),
        migrations.AddField(
            model_name='branch',
            name='google_map',
            field=models.URLField(blank=True),
        ),
    ]
