# Generated by Django 6.0.6 on 2026-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_branch_contactmessage_event_faq_feature_galleryimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='services',
            field=models.ManyToManyField(blank=True, to='main_app.service'),
        ),
    ]
