# Generated by Django 6.0.6 on 2026-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_businessregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistration',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='business_registrations', to='main_app.service'),
        ),
    ]
