# Generated by Django 6.0.6 on 2026-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_businessregistration_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistration',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='main_app.service'),
        ),
    ]
