# Generated by Django 6.0.6 on 2026-07-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_booking_duration_remove_booking_duration_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
