# Generated by Django 6.0.7 on 2026-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_meetingroom_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='office',
            name='price_per_month',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
