# Generated by Django 6.0.7 on 2026-07-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_booking_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='owner_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='services',
            field=models.ManyToManyField(to='main_app.service'),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
