# Generated by Django 6.0.7 on 2026-07-20 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_businessregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/'),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Government Approval'), ('active', 'Active Virtual Office'), ('rejected', 'Application Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='commercial_registration',
            field=models.CharField(blank=True, help_text='Leave blank if this is a new CR.', max_length=100),
        ),
    ]
