# Generated by Django 6.0.7 on 2026-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_businessregistration_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='businessregistration',
            name='services',
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='cpr_document',
            field=models.FileField(blank=True, help_text='Upload copy of CPR.', null=True, upload_to='business_docs/cpr/'),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='cpr_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='passport_document',
            field=models.FileField(blank=True, help_text='Upload copy of Passport.', null=True, upload_to='business_docs/passport/'),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Registration'), ('renewal', 'CR Renewal')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='commercial_registration',
            field=models.CharField(blank=True, help_text='Required for renewals.', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Government Approval'), ('active', 'Active CR'), ('rejected', 'Application Rejected')], default='pending', max_length=20),
        ),
    ]
