# Generated by Django 6.0.7 on 2026-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_businessregistration_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('virtual', 'Virtual Office'), ('serviced', 'Serviced Office'), ('coworking', 'Coworking Space'), ('meeting', 'Meeting Room'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
