# Generated by Django 6.0.7 on 2026-07-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
    ]
