# Generated by Django 6.0.7 on 2026-07-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='available',
        ),
        migrations.RemoveField(
            model_name='office',
            name='available',
        ),
    ]
