# Generated by Django 6.0.7 on 2026-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_meetingroom_available_remove_office_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branches/'),
        ),
    ]
